### PR TITLE
fix build on Ruby 3

### PR DESCRIPTION
**Pull request by tenderlove**
Hi,

This gem doesn't build on Ruby 3.  If I try to build on Ruby 3.0, I get the following errors:

```
../../../../ext/termios.c:311:5: error: use of undeclared identifier 'OpenFile'
    OpenFile *fptr;
    ^
../../../../ext/termios.c:311:15: error: use of undeclared identifier 'fptr'
    OpenFile *fptr;
              ^
../../../../ext/termios.c:314:21: error: use of undeclared identifier 'fptr'
    GetOpenFile(io, fptr);
                    ^
```

The patch in this PR makes the gem build again.

Thanks!

### CODE REVIEW

**Comment by arika** [comment]
Thank you 😃
